# Generated by Django 5.0.3 on 2024-03-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=10)),
                ("Age", models.IntegerField()),
                ("Place", models.CharField(max_length=15)),
            ],
        ),
    ]
